name: money_tracker
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  get: ^4.6.6
  animated_bottom_navigation_bar: ^1.3.3
  crypto: ^3.0.5
  flutter_localizations:
    sdk: flutter
  
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  path_provider: ^2.1.3
  path: ^1.9.0
  animations: ^2.0.11
  toggle_switch: ^2.3.0
  uuid: ^4.4.2
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  # device_preview: ^1.2.0
  

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Animation.json"
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/iconWallets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500

