import 'package:get/get.dart';

class Localization extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': "Hello",
      "spending": "Spending",
      "income": "Income",
      "home" : "Home", 
      "wallet" : "Wallet",
      'input' : "Input",
      "report" : "Report",
      "other" : "Other",
      "setting": "General settings",
      "logout": "Log out",
      "financial_statement": "Financial statement",
      "expense_income": "Expense vs Income",
      "expense_analysis": "Expense analysis",
      "income_analysis": "Income analysis",
      "moneny_lent_borrowed": "Money lent/borrowed",
      "payee_payer": "Payee/Payer",
      "event": "Event",
      "financial_analysis": "Financial Analysis",
      "save": "Save",
      "description": "Description",
      'text_auth_phone': 'Enter phone',
      'text_auth_username': 'Enter username',
      'text_auth_password': 'Enter password',
      'signin': 'Sign in',
      'signout': 'Sign up', 
      "link_register_account": "Register account",
      "link_login_account": "Login account", 
      'icon_currency': "\đ",
      'date' : 'Date',
      'select_title_wallets_create_transaction': "Select wallet type",
      "title_navigation_1": "Wallet information",
      "title_navigation_4": "Create transaction",
      "lable_wallet_total": "Total",
      "title_select_wallet": "Select wallet type",
      'select_wallet_1': "Savings Wallet",
      'select_wallet_2': "Cash Wallet",
      'select_wallet_3': "Credit Card",
      'select_wallet_4': "Home",
      'select_wallet_5': "Car",
      'select_wallet_6': "Entertainment",
    },
    'vi_VN': {
      'date' : 'Ngày tạo',
      'hello': "Chào",
      "spending": "Chi tiêu",
      "income": "Thu nhập",
      "home" : "Tổng quan",
      "wallet" : "Ví",
      'input' : "Nhập",
      "report" : "Báo cáo",
      "other" : "Khác",
      "setting": "Cài đặt chung",
      "logout": "Đăng xuất",
      "financial_statement": "Tài chính hiện tại",
      "expense_income": "Tình hình thu chi",
      "expense_analysis": "Phân tích chi tiêu",
      "income_analysis": "Phân tích thu",
      "moneny_lent_borrowed": "Theo dõi vay nợ",
      "payee_payer": "Đối tượng thu/chi",
      "event": "Chuyến đi/Sự kiện",
      "financial_analysis": "Phân tích tài chính",
      "save": "Lưu",
      "description": "Mô tả",
      'text_auth_phone': 'Nhập số điện thoại',
      'text_auth_username': 'Nhập tài khoản',
      'text_auth_password': 'Nhập mật khẩu',
      'signin': 'Đăng nhập',
      'signout': 'Đăng ký',
      "link_register_account": "Đăng ký tài khoản",
      "link_login_account": "Đăng nhập tài khoản",
      'icon_currency': "đ",
      'select_title_wallets_create_transaction': "Chọn loại ví", 
      "title_navigation_4": "Tạo giao dịch",
      "title_navigation_1": "Thông tin ví",
      "lable_wallet_total": "Tổng",
      "title_select_wallet": "Chọn loại ví",
      'select_wallet_1': "Ví tiết kiệm",
      'select_wallet_2': "Ví tiền mặt",
      'select_wallet_3': "Thẻ tín dụng",
      'select_wallet_4': "Nhà",
      'select_wallet_5': "Xe",
      'select_wallet_6': "Giải trí",
    }
  };
} 