import 'package:get/get.dart';

class Localization extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': "Hello",
      "spending": "Spending",
      "income": "Income",
      "home" : "Home", 
      "wallet" : "Wallet",
      'input' : "Input",
      "report" : "Report",
      "other" : "Other",
      "setting": "General settings",
      "logout": "Log out",
      "financial_statement": "Financial statement",
      "expense_income": "Expense vs Income",
      "expense_analysis": "Expense analysis",
      "income_analysis": "Income analysis",
      "moneny_lent_borrowed": "Money lent/borrowed",
      "payee_payer": "Payee/Payer",
      "event": "Event",
      "financial_analysis": "Financial Analysis",
      "save": "Save",
      "description": "Description",
      'text_auth_phone': 'Input phone',
      'text_auth_username': 'Input username',
      'text_auth_password': 'Input password',
      'signin': 'Sign in',
      'signout': 'Sign up', 
      "link_register_account": "Register account",
      "link_login_account": "Login account", 
      'icon_currency': "\$",
    },
    'vi_VN': {
      'hello': "Chào",
      "spending": "Chi tiêu",
      "income": "Thu nhập",
      "home" : "Tổng quan",
      "wallet" : "Ví",
      'input' : "Nhập",
      "report" : "Báo cáo",
      "other" : "Khác",
      "setting": "Cài đặt chung",
      "logout": "Đăng xuất",
      "financial_statement": "Tài chính hiện tại",
      "expense_income": "Tình hình thu chi",
      "expense_analysis": "Phân tích chi tiêu",
      "income_analysis": "Phân tích thu",
      "moneny_lent_borrowed": "Theo dõi vay nợ",
      "payee_payer": "Đối tượng thu/chi",
      "event": "Chuyến đi/Sự kiện",
      "financial_analysis": "Phân tích tài chính",
      "save": "Lưu",
      "description": "Mô tả",
      'text_auth_phone': 'Nhập số điện thoại',
      'text_auth_username': 'Nhập tài khoản',
      'text_auth_password': 'Nhập mật khẩu',
      'signin': 'Đăng nhập',
      'signout': 'Đăng ký',
      "link_register_account": "Đăng ký tài khoản",
      "link_login_account": "Đăng nhập tài khoản",
      'icon_currency': "đ",
    }
  };
} 